### ISSUE TITLE
where can I find _pywrapfst.h ?

### ISSUE THREAD

**Issue by kamirdin** [mmcauliffe/kalpy#11]
Hi, I failed to install kalpy by `conda install kalpy` somehow
then I use `python3 setup install ` at kalpy root dir, after install kaldi toolkit successfully,
but got Error :can't find file _pywrapfst.h,
I checked https://github.com/conda-forge/pynini-feedstock and https://github.com/kylebgorman/pynini/tree/master/extensions
where can I find this file ? thank you !

**Comment by mmcauliffe** [comment]
It's a generated file from https://github.com/conda-forge/pynini-feedstock/blob/main/recipe/patches/0002-Add-API-declarations.patch, so if you install pynini via `conda install pynini` then it should be in your `CONDA_ENV_ROOT/include` directory.  Then see https://github.com/conda-forge/kalpy-feedstock/blob/main/recipe/build.sh#L11 (or https://github.com/conda-forge/kalpy-feedstock/blob/main/recipe/bld.bat#L3 for windows) for setting the path of KALDI_ROOT to your conda environment directory.

**Comment by vytskalt** [comment]
> It's a generated file from https://github.com/conda-forge/pynini-feedstock/blob/main/recipe/patches/0002-Add-API-declarations.patch, so if you install pynini via `conda install pynini` then it should be in your `CONDA_ENV_ROOT/include` directory. Then see https://github.com/conda-forge/kalpy-feedstock/blob/main/recipe/build.sh#L11 (or https://github.com/conda-forge/kalpy-feedstock/blob/main/recipe/bld.bat#L3 for windows) for setting the path of KALDI_ROOT to your conda environment directory.

Hi, I ran into this same error while packaging kalpy for [nixpkgs](https://github.com/NixOS/nixpkgs/). Am I correct to assume that if I apply the patch you linked to pynini the _pywrapfst.h file will be generated correctly during build time?

**Comment by myamusashi** [comment]
> > It's a generated file from https://github.com/conda-forge/pynini-feedstock/blob/main/recipe/patches/0002-Add-API-declarations.patch, so if you install pynini via `conda install pynini` then it should be in your `CONDA_ENV_ROOT/include` directory. Then see https://github.com/conda-forge/kalpy-feedstock/blob/main/recipe/build.sh#L11 (or https://github.com/conda-forge/kalpy-feedstock/blob/main/recipe/bld.bat#L3 for windows) for setting the path of KALDI_ROOT to your conda environment directory.
> 
> Hi, I ran into this same error while packaging kalpy for [nixpkgs](https://github.com/NixOS/nixpkgs/). Am I correct to assume that if I apply the patch you linked to pynini the _pywrapfst.h file will be generated correctly during build time?

Did you do it? Did it work?
